# Generated by Django 5.2.1 on 2025-05-16 00:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaggedPenguin",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="RFID Tag ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tagged Penguin",
                "verbose_name_plural": "Tagged Penguins",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kilograms",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="penguin_measurements/%Y/%m/%d/",
                        verbose_name="Penguin Image",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Exact time from microcontroller (Local time)",
                        verbose_name="Measurement Time",
                    ),
                ),
                (
                    "penguin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="tracker.taggedpenguin",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("penguin", "timestamp"),
                        name="unique_measurement_per_penguin_time",
                    )
                ],
            },
        ),
    ]
