# Generated by Django 5.2.1 on 2025-05-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("automatic", "Automatic")],
                default="automatic",
                help_text="Source of the measurement",
                max_length=10,
            ),
        ),
    ]
