# Generated by Django 5.2.1 on 2025-05-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_measurement_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="image",
            field=models.ImageField(
                upload_to="p_images/", verbose_name="Penguin Image"
            ),
        ),
    ]
