# Generated by Django 5.2.1 on 2025-05-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_measurement_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="taggedpenguin",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Penguin Name"
            ),
        ),
    ]
