# Generated by Django 5.2.1 on 2025-05-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_taggedpenguin_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measurement",
            name="id",
        ),
        migrations.AlterField(
            model_name="measurement",
            name="timestamp",
            field=models.DateTimeField(
                help_text="Exact time from microcontroller (Local time)",
                primary_key=True,
                serialize=False,
                verbose_name="Measurement Time",
            ),
        ),
    ]
